export const weatherSignatures: Record<number, any> = {
    0: {
        label: "Clear",
        skyGradient: 'linear-gradient(to bottom, #2980B9, #6DD5FA)',
        particleType: 'none',
        particleCount: 0,
        cloudOpacity: 0,
        cloudBlur: 0,
        mistOpacity: 0
    },
    1: {
        label: "Mainly Clear",
        skyGradient: 'linear-gradient(to bottom, #4CA1AF, #89D4E8)',
        particleType: 'none',
        particleCount: 0,
        cloudOpacity: 0.2,
        cloudBlur: 2,
        mistOpacity: 0
    },
    2: {
        label: "Partly Cloudy",
        skyGradient: 'linear-gradient(to bottom, #5F7D95, #A8C0D6)',
        particleType: 'none',
        particleCount: 0,
        cloudOpacity: 0.5,
        cloudBlur: 3,
        mistOpacity: 0.1
    },
    3: {
        label: "Overcast",
        skyGradient: 'linear-gradient(to bottom, #757F9A, #D7DDE8)',
        particleType: 'none',
        particleCount: 0,
        cloudOpacity: 1.0,
        cloudBlur: 4,
        mistOpacity: 0.2
    },
    45: {
        label: "Fog",
        skyGradient: 'linear-gradient(to bottom, #B7C3CC, #D7DDE8)',
        particleType: 'none',
        particleCount: 0,
        cloudOpacity: 0.3,
        cloudBlur: 20,
        mistOpacity: 0.9
    },
    48: {
        label: "Depositing Rime Fog",
        skyGradient: 'linear-gradient(to bottom, #9BA5B0, #C4CCD6)',
        particleType: 'snow',
        particleCount: 20,
        particleSpeed: 0.2,
        particleSize: 1,
        cloudOpacity: 0.4,
        cloudBlur: 18,
        mistOpacity: 0.85
    },
    51: {
        label: "Light Drizzle",
        skyGradient: 'linear-gradient(to bottom, #3E5151, #DECBA4)',
        particleType: 'rain',
        particleCount: 30,
        particleSpeed: 0.4,
        particleLength: 6,
        particleOpacity: 0.3,
        cloudOpacity: 0.7,
        cloudBlur: 8,
        mistOpacity: 0
    },
    53: {
        label: "Moderate Drizzle",
        skyGradient: 'linear-gradient(to bottom, #2C3E50, #BDC3C7)',
        particleType: 'rain',
        particleCount: 50,
        particleSpeed: 0.6,
        particleLength: 8,
        particleOpacity: 0.4,
        cloudOpacity: 0.8,
        cloudBlur: 10,
        mistOpacity: 0.1
    },
    55: {
        label: "Dense Drizzle",
        skyGradient: 'linear-gradient(to bottom, #2C3E50, #BDC3C7)',
        particleType: 'rain',
        particleCount: 80,
        particleSpeed: 0.8,
        particleLength: 10,
        particleOpacity: 0.5,
        cloudOpacity: 0.9,
        cloudBlur: 12,
        mistOpacity: 0.2
    },
    56: {
        label: "Light Freezing Drizzle",
        skyGradient: 'linear-gradient(to bottom, #434343, #B4B4B4)',
        particleType: 'rain',
        particleCount: 40,
        particleSpeed: 0.5,
        particleLength: 7,
        particleOpacity: 0.6,
        cloudOpacity: 0.8,
        cloudBlur: 9,
        mistOpacity: 0.15
    },
    57: {
        label: "Dense Freezing Drizzle",
        skyGradient: 'linear-gradient(to bottom, #2E3436, #8D9499)',
        particleType: 'rain',
        particleCount: 70,
        particleSpeed: 0.7,
        particleLength: 9,
        particleOpacity: 0.65,
        cloudOpacity: 0.95,
        cloudBlur: 11,
        mistOpacity: 0.25
    },
    61: {
        label: "Slight Rain",
        skyGradient: 'linear-gradient(to bottom, #4B6584, #A8B8C8)',
        particleType: 'rain',
        particleCount: 60,
        particleSpeed: 1.0,
        particleLength: 15,
        particleOpacity: 0.45,
        cloudOpacity: 0.75,
        cloudBlur: 10,
        mistOpacity: 0
    },
    63: {
        label: "Moderate Rain",
        skyGradient: 'linear-gradient(to bottom, #364F6B, #7C8FA3)',
        particleType: 'rain',
        particleCount: 100,
        particleSpeed: 1.4,
        particleLength: 25,
        particleOpacity: 0.55,
        cloudOpacity: 0.85,
        cloudBlur: 12,
        mistOpacity: 0.1
    },
    65: {
        label: "Heavy Rain",
        skyGradient: 'linear-gradient(to bottom, #232526, #414345)',
        particleType: 'rain',
        particleCount: 150,
        particleSpeed: 1.8,
        particleLength: 35,
        particleOpacity: 0.6,
        cloudOpacity: 1.0,
        cloudBlur: 15,
        mistOpacity: 0.2
    },
    66: {
        label: "Light Freezing Rain",
        skyGradient: 'linear-gradient(to bottom, #3D4E5A, #8A9BA8)',
        particleType: 'rain',
        particleCount: 70,
        particleSpeed: 1.1,
        particleLength: 18,
        particleOpacity: 0.65,
        cloudOpacity: 0.8,
        cloudBlur: 11,
        mistOpacity: 0.15
    },
    67: {
        label: "Heavy Freezing Rain",
        skyGradient: 'linear-gradient(to bottom, #1C2833, #5D6D7E)',
        particleType: 'rain',
        particleCount: 120,
        particleSpeed: 1.5,
        particleLength: 28,
        particleOpacity: 0.7,
        cloudOpacity: 0.95,
        cloudBlur: 14,
        mistOpacity: 0.25
    },
    71: {
        label: "Slight Snow",
        skyGradient: 'linear-gradient(to bottom, #E0E5E8, #C4D4DD)',
        particleType: 'snow',
        particleCount: 40,
        particleSpeed: 0.5,
        particleSize: 3,
        particleSway: 1.5,
        cloudOpacity: 0.7,
        cloudBlur: 8,
        mistOpacity: 0.1
    },
    73: {
        label: "Moderate Snow",
        skyGradient: 'linear-gradient(to bottom, #D5DBE0, #AAB8C2)',
        particleType: 'snow',
        particleCount: 80,
        particleSpeed: 0.7,
        particleSize: 4,
        particleSway: 2,
        cloudOpacity: 0.85,
        cloudBlur: 10,
        mistOpacity: 0.2
    },
    75: {
        label: "Heavy Snow",
        skyGradient: 'linear-gradient(to bottom, #C5CDD4, #8E99A3)',
        particleType: 'snow',
        particleCount: 140,
        particleSpeed: 1.0,
        particleSize: 5,
        particleSway: 2.5,
        cloudOpacity: 1.0,
        cloudBlur: 12,
        mistOpacity: 0.3
    },
    77: {
        label: "Snow Grains",
        skyGradient: 'linear-gradient(to bottom, #E6DADA, #274046)',
        particleType: 'snow',
        particleCount: 60,
        particleSpeed: 0.8,
        particleSize: 2,
        particleSway: 0,
        cloudOpacity: 0.9,
        cloudBlur: 10,
        mistOpacity: 0.15
    },
    80: {
        label: "Slight Rain Showers",
        skyGradient: 'linear-gradient(to bottom, #536976, #BBD2C5)',
        particleType: 'rain',
        particleCount: 70,
        particleSpeed: 1.3,
        particleLength: 20,
        particleOpacity: 0.5,
        cloudOpacity: 0.6,
        cloudBlur: 9,
        mistOpacity: 0
    },
    81: {
        label: "Moderate Rain Showers",
        skyGradient: 'linear-gradient(to bottom, #485563, #8FA3AD)',
        particleType: 'rain',
        particleCount: 110,
        particleSpeed: 1.6,
        particleLength: 28,
        particleOpacity: 0.55,
        cloudOpacity: 0.75,
        cloudBlur: 11,
        mistOpacity: 0.1
    },
    82: {
        label: "Violent Rain Showers",
        skyGradient: 'linear-gradient(to bottom, #1A1C20, #3A3D42)',
        particleType: 'rain',
        particleCount: 180,
        particleSpeed: 2.2,
        particleLength: 40,
        particleOpacity: 0.7,
        cloudOpacity: 1.0,
        cloudBlur: 16,
        mistOpacity: 0.3
    },
    85: {
        label: "Slight Snow Showers",
        skyGradient: 'linear-gradient(to bottom, #DAE2E8, #B8C6D1)',
        particleType: 'snow',
        particleCount: 60,
        particleSpeed: 0.9,
        particleSize: 4,
        particleSway: 2,
        cloudOpacity: 0.7,
        cloudBlur: 9,
        mistOpacity: 0.15
    },
    86: {
        label: "Heavy Snow Showers",
        skyGradient: 'linear-gradient(to bottom, #C2CCD6, #98A5B0)',
        particleType: 'snow',
        particleCount: 120,
        particleSpeed: 1.2,
        particleSize: 5,
        particleSway: 2.5,
        cloudOpacity: 0.9,
        cloudBlur: 12,
        mistOpacity: 0.25
    },
    95: {
        label: "Thunderstorm",
        skyGradient: 'linear-gradient(to bottom, #1F1C2C, #464159)',
        particleType: 'rain',
        particleCount: 130,
        particleSpeed: 2.0,
        particleLength: 32,
        particleOpacity: 0.65,
        cloudOpacity: 1.0,
        cloudBlur: 14,
        mistOpacity: 0.2,
        lightning: true
    },
    96: {
        label: "Thunderstorm with Slight Hail",
        skyGradient: 'linear-gradient(to bottom, #242124, #3C3847)',
        particleType: 'mixed',
        particleCount: 140,
        particleSpeed: 2.1,
        particleLength: 30,
        particleOpacity: 0.7,
        cloudOpacity: 1.0,
        cloudBlur: 15,
        mistOpacity: 0.25,
        lightning: true
    },
    99: {
        label: "Thunderstorm with Heavy Hail",
        skyGradient: 'linear-gradient(to bottom, #0F0E11, #2B2833)',
        particleType: 'mixed',
        particleCount: 170,
        particleSpeed: 2.4,
        particleLength: 35,
        particleOpacity: 0.75,
        cloudOpacity: 1.0,
        cloudBlur: 18,
        mistOpacity: 0.35,
        lightning: true
    }
};